# Generated by Django 5.0.7 on 2024-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_managers_alter_orderitem_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
