# Generated by Django 5.0.7 on 2024-12-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
