# Generated by Django 5.0.7 on 2025-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_order_ref_alter_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specifications',
            field=models.TextField(default='', max_length=250),
        ),
    ]
