# Generated by Django 5.0.7 on 2024-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
    ]
