# Generated by Django 5.0.7 on 2024-08-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_wishlist_delete_userwishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
