# Generated by Django 5.0.7 on 2024-10-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_created_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
