# Generated by Django 5.0.7 on 2024-10-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_is_deal_of_the_day_dealoftheday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealoftheday',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='dealoftheday',
            old_name='number_of_avalable_stock',
            new_name='number_of_available_stock',
        ),
    ]
