# Generated by Django 5.0.7 on 2024-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_color'),
        ('product', '0014_alter_productreview_rating_topshopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='product_colors', to='crm.color'),
        ),
    ]
