# Generated by Django 5.0.7 on 2024-12-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealoftheday',
            name='discount_percentage',
        ),
    ]
