# Generated by Django 5.0.7 on 2024-12-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_dealoftheday_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealoftheday',
            name='number_of_available_stock',
        ),
    ]
