# Generated by Django 5.0.7 on 2024-08-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
